twitch_username : "your account name here"
twitch_oauth : "oauth:twitch oauth"
client_id : "your twitch client id here"
twitch_channels :
- "animaggus"
- "collectablecat"
youtube_enabled : True
screen_width : 1280
screen_height : 720
